name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-14, macos-15] # Build bottles for Apple Silicon
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run brew test-bot --only-cleanup-before
        run: brew test-bot --only-cleanup-before

      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup

      # Test the Formula (CLI) and Build Bottles
      - name: Build Crawl Formula
        run: |
          brew test-bot --only-formulae --root-url=https://ghcr.io/v2/aritya-arjunan/crawl crawl

      # Test the Cask (GUI) - Casks are not bottled, just verified
      - name: Verify Crawl Cask
        run: |
          brew install --cask crawl-tiles

      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
